# Model Configuration File
# This file defines all available embedding and LLM models
# Only API-based models are supported (no local/open source models)

embedding_models:
  # OpenAI Embedding Models
  text-embedding-3-small:
    provider: openai
    dimension: 1536
    description: "OpenAI's fast and efficient embedding model"
    category: "External"
    recommended: true
    requires_api_key: true
    cost: "Paid"
    gateway_url: "https://api.openai.com/v1"

  text-embedding-3-large:
    provider: openai
    dimension: 3072
    description: "OpenAI's most capable embedding model"
    category: "Premium External"
    recommended: true
    requires_api_key: true
    cost: "Paid"
    gateway_url: "https://api.openai.com/v1"

  text-embedding-ada-002:
    provider: openai
    dimension: 1536
    description: "OpenAI's previous generation embedding model (legacy)"
    category: "External Legacy"
    recommended: false
    requires_api_key: true
    cost: "Paid"
    gateway_url: "https://api.openai.com/v1"

  # Google Embedding Models
  models/embedding-001:
    provider: google
    dimension: 768
    description: "Google's general-purpose embedding model"
    category: "External"
    recommended: true
    requires_api_key: true
    cost: "Free/Paid"
    gateway_url: "https://generativelanguage.googleapis.com/v1beta"

  models/text-embedding-004:
    provider: google
    dimension: 768
    description: "Google's latest text embedding model"
    category: "External"
    recommended: true
    requires_api_key: true
    cost: "Free/Paid"
    gateway_url: "https://generativelanguage.googleapis.com/v1beta"

llm_models:
  # OpenAI LLM Models
  openai:
    provider: openai
    description: "OpenAI GPT models for intelligent response generation (supports API Gateway via base_url)"
    requires_api_key: true
    supports_gateway: true
    gateway_url: "https://api.openai.com/v1"
    models:
      gpt-3.5-turbo:
        gateway_url: "https://api.openai.com/v1"
      gpt-4:
        gateway_url: "https://api.openai.com/v1"
      gpt-4-turbo-preview:
        gateway_url: "https://api.openai.com/v1"
      gpt-4o:
        gateway_url: "https://api.openai.com/v1"
      gpt-4o-mini:
        gateway_url: "https://api.openai.com/v1"
    default_model: gpt-4

  # Google LLM Models
  google:
    provider: google
    description: "Google Gemini models for intelligent response generation (supports API Gateway via base_url)"
    requires_api_key: true
    supports_gateway: true
    gateway_url: "https://generativelanguage.googleapis.com/v1beta"
    models:
      gemini-pro:
        gateway_url: "https://generativelanguage.googleapis.com/v1beta"
      gemini-pro-vision:
        gateway_url: "https://generativelanguage.googleapis.com/v1beta"
      gemini-1.5-pro:
        gateway_url: "https://generativelanguage.googleapis.com/v1beta"
      gemini-1.5-flash:
        gateway_url: "https://generativelanguage.googleapis.com/v1beta"
    default_model: gemini-pro

# Default configurations
defaults:
  embedding_model: text-embedding-3-small
  llm_provider: openai
  llm_model: gpt-4

# Configuration validation
validation:
  embedding_providers:
    - openai
    - google
  llm_providers:
    - openai
    - google